apps/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
   path('', views.view_cart, name='view_cart'),
   path('update_item/<int:item_id>/', views.update_item, name='update_item'),
   path('remove_item/<int:item_id>/', views.remove_item, name='remove_item'),
   path('checkout/', views.checkout, name='checkout'),
]

apps/cart_shop/urls.py
from django.urls import path
from .views import ViewCart, ViewWishlist, ViewCartBuy, ViewCartDel, ViewCartAdd, AddInWishList, WishListDel

app_name = 'cart_shop'

urlpatterns = [
    path('', ViewCart.as_view(), name='cart'),
    path('wishlist/', ViewWishlist.as_view(), name='wishlist'),
    path('buy/<int:product_id>', ViewCartBuy.as_view(), name='buy'),
    path('del/<int:item_id>', ViewCartDel.as_view(), name='del_from_cart'),
    path('add/<int:product_id>', ViewCartAdd.as_view(), name='add_to_cart'),
    path('wish/<int:product_id>', AddInWishList.as_view(), name='wish'),
    path('delwish/<int:item_id>', WishListDel.as_view(), name='del_from_wish'),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('other/', include('apps.login.urls')),
    path('other/cart/', include('apps.cart.urls')),
    path('other/', include('apps.common.urls')),
    path('random/', include('apps.test_app.urls')),
#Продуктовый магазин
    path('', include('apps.home.urls')),
    path('cart/', include('apps.cart_shop.urls')),
    path('blog/', include('apps.blog.urls')),
    path('checkout/', include('apps.checkout.urls')),
    path('shop/', include('apps.shop.urls')),
    path('login/', include('apps.auth_shop.urls')),
]

apps/cart/models.py
from django.db import models

# Create your models here.

from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Cart(models.Model):
   user = models.ForeignKey(User, on_delete=models.CASCADE)
   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)

   def __str__(self):
       return f"{self.user}"

class Product(models.Model):
   name = models.CharField(max_length=255)
   price = models.DecimalField(max_digits=10, decimal_places=2)
   description = models.TextField()
   image = models.ImageField(upload_to='static/products/', null=True, blank=True)
   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)

   def save(self, *args, **kwargs):
      super().save(*args, **kwargs)

      img = Image.open(self.image.path)
      img = img.resize((100, 100), Image.ANTIALIAS)
      img.save(self.image.path)

   def __str__(self):
       return self.name

class CartItem(models.Model):
   cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
   product = models.ForeignKey(Product, on_delete=models.CASCADE)
   quantity = models.IntegerField(default=1)
   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)

   def __str__(self):
       return f"{self.cart}_{self.product}"

apps/cart_shop/models.py
from django.db import models
from django.contrib.auth.models import User
from apps.cart.models import Cart


class Product(models.Model):
    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    discount = models.IntegerField(null=True, blank=True)
    description = models.TextField()
    image = models.ImageField(upload_to='static/shop/images',
                              null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class CartItemShop(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class WishList(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.cart}_{self.product}"

apps/cart/views.py
from django.shortcuts import render

from django.shortcuts import render, redirect
from .models import Cart, CartItem


def view_cart(request):
   cart_items = CartItem.objects.filter(cart__user=request.user)
   total_price = sum(item.product.price * item.quantity for item in cart_items)
   context = {'cart_items': cart_items, 'total_price': total_price}
   return render(request, 'cart/cart.html', context)


def update_item(request, item_id):
   item = CartItem.objects.get(id=item_id)
   item.quantity += int(request.GET.get('quantity'))
   item.save()
   return redirect('cart:view_cart')


def remove_item(request, item_id):
   CartItem.objects.filter(id=item_id).delete()
   return redirect('cart:view_cart')


def checkout(request):
   # code to handle checkout process
   return redirect('cart:view_cart')


# Create your views here.

apps/cart_shop/views.py
from django.views import View
from .models import CartItemShop, Cart, Product, WishList
from django.shortcuts import render, get_object_or_404, redirect
from apps.cart.models import Cart
from decimal import Decimal


class ViewWishlist(View):
    def get(self, request):
        items_carts = WishList.objects.filter(cart__user=request.user)
        data = list(items_carts)
        context = {'items_carts': data,
                   }
        return render(request, 'cart_shop/wishlist.html', context)

class ViewCart(View):
    def get(self, request):
        cart_items = CartItemShop.objects.filter(cart__user=request.user)
        data = list(cart_items)
        total_price_no_discount = sum(item.product.price * item.quantity
                                      for item in data)
        if not total_price_no_discount:
            total_price_no_discount = Decimal("0.00")

        total_discount = sum(item.product.price * item.product.discount * item.quantity
                             for item in data if item.product.discount is not None) / 100
        if not total_discount:
            total_discount = Decimal("0.00")
        total_sum = total_price_no_discount - total_discount
        context = {'cart_items': data,
                   'total_price_no_discount': total_price_no_discount,
                   'total_discount': total_discount,
                   'total_sum': total_sum,
                   }
        return render(request, 'cart_shop/cart.html', context)


def save_product_in_cart(request, product_id):
    cart_items = CartItemShop.objects.filter(cart__user=request.user,
                                             product__id=product_id)
    if cart_items:
        cart_item = cart_items[0]
        cart_item.quantity += 1
    else:
        product = get_object_or_404(Product, id=product_id)
        cart_user = get_object_or_404(Cart, user=request.user)
        cart_item = CartItemShop(cart=cart_user, product=product)
    cart_item.save()

class ViewCartBuy(View):
    def get(self, request, product_id):
        save_product_in_cart(request, product_id)
        return redirect('cart_shop:cart')


class ViewCartDel(View):
    def get(self, request, item_id):
        cart_item = get_object_or_404(CartItemShop, id=item_id)
        cart_item.delete()
        return redirect('cart_shop:cart')


class ViewCartAdd(View):
    def get(self, request, product_id):
        save_product_in_cart(request, product_id)
        return redirect('home:index')

class AddInWishList(View):
    def get(self, request, product_id):
        if str(request.user) == 'AnonymousUser':
            return redirect('auth_shop:login')
        else:
            cart_items = WishList.objects.filter(cart__user=request.user,
                                                 product__id=product_id)
            if cart_items:
                cart_item = cart_items[0]
                cart_item.quantity = 1
            else:
                product = get_object_or_404(Product, id=product_id)
                cart_user = get_object_or_404(Cart, user=request.user)
                cart_item = WishList(cart=cart_user, product=product)
            cart_item.save()
            return redirect('cart_shop:wishlist')

#AnonymousUser


class WishListDel(View):
    def get(self, request, item_id):
        cart_item = get_object_or_404(WishList, id=item_id)
        cart_item.delete()
        return redirect('cart_shop:wishlist')

apps/cart_shop/templates/cart_shop/wishlist.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
    <div class="hero-wrap hero-bread" style="background-image: url({% static 'shop/images/bg_1.jpg' %});">
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
          	<p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Wishlist</span></p>
            <h1 class="mb-0 bread">My Wishlist</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section ftco-cart">
			<div class="container">
				<div class="row">
    			<div class="col-md-12 ftco-animate">
    				<div class="cart-list">
	    				<table class="table">
						    <thead class="thead-primary">
						      <tr class="text-center">
						        <th>&nbsp;</th>
						        <th>Product List</th>
						        <th>&nbsp;</th>
						        <th>Price</th>
						        <th>Quantity</th>
						        <th>Total</th>
						      </tr>
						    </thead>
						    <tbody>
							{% for item in items_carts %}
						      <tr class="text-center">
						        <td class="product-remove"><a href="{% url 'cart_shop:del_from_wish' item.id %}"><span class="ion-ios-close"></span></a></td>

						        <td class="image-prod"><div class="img" style="background-image:url({{item.product.image.url}});"></div></td>

						        <td class="product-name">
						        	<h3>{{item.product.name}}</h3>
						        	<p>{{item.product.description}}</p>
						        </td>

						        <td class="price">{{item.product.price}}</td>

						        <td class="quantity">
						        	<div class="input-group mb-3">
					             	<input type="text" name="quantity" class="quantity form-control input-number" value="1" min="1" max="100">
					          	</div>
					          </td>

						        <td class="total">${% widthratio item.product.price 1 item.quantity %}</td>
						      </tr><!-- END yyyyyyyyyyyyyTR-->
							{%endfor%}
						    </tbody>
						  </table>
					  </div>
    			</div>
    		</div>
			</div>
		</section>

{% endblock %}